import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapScripts from "./components/BootstrapScripts";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resolve Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-wEmeIV1mKuiNpO9K3z6tAKyhf1Fw5IS1ntOMqowLb9bbO0i1mTDVJ6f4i0A1evxN"
          crossOrigin="anonymous"
        />
      </Head>
      <body className={inter.className}>
        {children}
        <BootstrapScripts />
      </body>
    </html>
  );
}
